targets:
  $default:
    builders:
      gen_models:genBuilder:
        enabled: true
        options:
          build_extensions:
            '.dart': '.g1.dart'
#      gen_models:mergeBuilder:
#        enabled: true
#        options:
#          build_extensions:
#            '.dart': '.g1.dart'

builders:
  genBuilder:
    import: "package:gen_models/builder.dart"
    builder_factories: ["genBuilder"]
    build_extensions:
      ".dart": [".gen.dart"]
    auto_apply: dependents
    build_to: source
    runs_before: ["gen_models|mergeBuilder"]
    defaults:
      options:
        output_dir: "lib/gen"
#  mergeBuilder:
#    import: "package:gen_models/merge_files.dart"
#    builder_factories: ["mergeBuilder"]
#    build_extensions:
#      ".dart": [".gen.dart"]
#    auto_apply: dependents
#    build_to: source
#    required_inputs:
#      - "**/*.mapper.dart"
#    defaults:
#      options:
#        output_dir: "lib/gen"