targets:
  $default:
    builders:
      gen_models|genBuilder:
        enabled: true

builders:
  genBuilder:
    import: "package:gen_models/builder.dart"
    builder_factories: ["genBuilder"]
    build_extensions: {".dart": ["g.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: []